#!/bin/sh
r2plus=~/.config/r2modmanPlus-local
profiles=$r2plus/Valheim/profiles
dev=$profiles/Dev/BepInEx
bwf=$dev/plugins/Solykos-BuildWithFrostner
mkdir $bwf
cp -r *.dll manifest.json icon.png $bwf/

